//@ts-nocheck
export const volumeUnits = ['ml', 'L', 'g', 'kg', 'pcs'];
export const works = 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=80&q=80';

export const altProducts: Product[] = [
    {
        id: 1,
        name: 'Classic Date Syrup',
        slug: 'classic-date-syrup',
        price: 2200,
        status: 'active',
        image: works,
        variations: 3,
    },
    {
        id: 2,
        name: 'Cocoa Date Syrup',
        slug: 'cocoa-date-syrup',
        price: 2500,
        status: 'active',
        image: works,
        variations: 2,
    },
    {
        id: 3,
        name: 'Ginger Date Syrup',
        slug: 'ginger-date-syrup',
        price: 2400,
        status: 'inactive',
        image: works,
        variations: 4,
    },
    {
        id: 4,
        name: 'Vanilla Date Syrup',
        slug: 'vanilla-date-syrup',
        price: 2600,
        status: 'active',
        image: works,
        variations: 1,
    },
    {
        id: 5,
        name: 'Spiced Date Syrup',
        slug: 'spiced-date-syrup',
        price: 2700,
        status: 'inactive',
        image: works,
        variations: 5,
    },
    {
        id: 6,
        name: 'Cinnamon Date Syrup',
        slug: 'cinnamon-date-syrup',
        price: 2800,
        status: 'active',
        image: works,
        variations: 0,
    },
    {
        id: 7,
        name: 'Caramel Date Syrup',
        slug: 'caramel-date-syrup',
        price: 2900,
        status: 'active',
        image: works,
        variations: 3,
    },
    {
        id: 8,
        name: 'Mint Date Syrup',
        slug: 'mint-date-syrup',
        price: 2550,
        status: 'inactive',
        image: works,
        variations: 2,
    },
    {
        id: 9,
        name: 'Orange Date Syrup',
        slug: 'orange-date-syrup',
        price: 2650,
        status: 'active',
        image: works,
        variations: 4,
    },
    {
        id: 10,
        name: 'Honey Date Syrup',
        slug: 'honey-date-syrup',
        price: 3000,
        status: 'active',
        image: works,
        variations: 3,
    },
];

export const productFields: any = [
    {
        name: 'name',
        label: 'Product Name',
        type: 'text',
        required: true,
        row: 1,
        col: 1,
        placeholder: 'e.g. Classic Date Syrup',
    },
    {
        name: 'category_id',
        label: 'Category',
        type: 'number',
        required: false,
        row: 2,
        col: 1,
        placeholder: 'Category ID',
    },
    {
        name: 'price',
        label: 'Price (₦)',
        type: 'number',
        required: true,
        min: 0,
        step: 0.01,
        row: 3,
        col: 1,
        placeholder: 'e.g. 2500',
    },
    {
        name: 'status',
        label: 'Status',
        type: 'select',
        required: false,
        // defaultValue: 'inactive',
        options: [
            { label: 'Active', value: 'active' },
            { label: 'Inactive', value: 'inactive' },
        ],
        row: 4,
        col: 1,
        defaultValue: 'active',
    },
    {
        name: 'stock',
        label: 'Stock',
        type: 'number',
        required: true,
        min: 0,
        row: 5,
        col: 1,
        defaultValue: 10,
        placeholder: 'Available stock',
    },
    {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        required: false,
        row: 6,
        col: 1,
        placeholder: 'Brief product description',
    },
    {
        name: 'image',
        label: 'Product Image',
        type: 'image',
        required: false,
        row: 7,
        col: 1,
    },
];

export type Categories = { id: number; name: string }[];

export const fields = (categories: Categories): FieldConfig[] => [
    {
        name: 'name',
        label: 'Product Name',
        type: 'text',
        placeholder: 'e.g. Date Syrup Deluxe',
    },
    {
        name: 'price',
        label: 'Price (₦)',
        type: 'text',
        placeholder: 'e.g. 2500',
    },
    {
        name: 'category_id',
        label: 'Category',
        type: 'select',
        options: categories.map((c) => ({ value: c.id, label: c.name })),
    },
    {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
            { value: 'active', label: 'Active' },
            { value: 'draft', label: 'Draft' },
            { value: 'archived', label: 'Archived' },
        ],
    },
    {
        name: 'weight',
        label: 'Weight (g)',
        type: 'text',
        placeholder: 'e.g. 500',
    },
    {
        name: 'description',
        label: 'Description',
        type: 'textarea',
        placeholder: 'Describe your product…',
    },
    {
        name: 'image',
        label: 'Product Image',
        type: 'image',
    },
];
